CREATE DATABASE IF NOT EXISTS institute_db CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

USE institute_db;

CREATE TABLE IF NOT EXISTS users (
    id INT AUTO_INCREMENT PRIMARY KEY,
    chat_id BIGINT UNIQUE NOT NULL,
    full_name VARCHAR(255) DEFAULT NULL,
    phone VARCHAR(20) DEFAULT NULL,
    question TEXT DEFAULT NULL,
    step VARCHAR(50) DEFAULT 'name',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
